feat: show only open jobs
fllstx/website pull request #47
Opened 2022-09-30 17:03 UTC by mojoaxel

2022-10-04 06:44 UTC, josurzyn requested changes
The 'Join us' button and the adverts in the team section are still there, which seems a bit inconsistent with removing the link to the 'Jobs' page.

Excited to hear if we've hired, or just aren't looking any more 😅

2022-10-04 06:44 UTC, josurzyn commented on src/jobs.njk
> +	<h2 class="open-positions-title">There are no open positions at this moment!</h2>
'at the moment' sounds a bit more natural, but you can leave it if you want

2022-10-04 06:44 UTC, josurzyn commented on src/jobs/angular-developer.md
> +open: false
I guess I've got some catching up to do!

2022-10-04 06:44 UTC, josurzyn commented on src/jobs/fullstack-developer.md
> +- Angular and node.js experiance
experience

2022-10-04 07:00 UTC, mojoaxel commented on src/jobs/angular-developer.md
> +open: false
I think we'll have one full and a half position filled at the end of next week :-)

2022-12-22 11:25 UTC, josurzyn approved these changes
Not sure why all the checks failed, but otherwise LGTM!

2022-12-22 11:25 UTC, josurzyn commented on src/jobs/angular-developer.md
> +- Possibility of using your choice of coworking-space
coworking space doesn't need a hyphen

2022-12-22 11:25 UTC, josurzyn commented on src/jobs/fullstack-developer.md
> +- Possibility of using your choice of coworking-space
no hyphen necessary

2022-12-22 14:23 UTC, merged

2022-12-22 14:55 UTC, mojoaxel commented
> Not sure why all the checks failed, but otherwise LGTM!

This was a netlify issue. The deprecated a build image we used.